from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 553)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuFile_2 = QtGui.QMenu(self.menubar)
        self.menuFile_2.setObjectName(_fromUtf8("menuFile_2"))
        self.menuView_2 = QtGui.QMenu(self.menubar)
        self.menuView_2.setObjectName(_fromUtf8("menuView_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSelect_Client = QtGui.QAction(MainWindow)
        self.actionSelect_Client.setObjectName(_fromUtf8("actionSelect_Client"))
        self.actionStart_Script = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.actionStart_Script.setIcon(icon)
        self.actionStart_Script.setObjectName(_fromUtf8("actionStart_Script"))
        self.actionLoad_Script = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.actionLoad_Script.setIcon(icon)
        self.actionLoad_Script.setObjectName(_fromUtf8("actionLoad_Script"))
        self.actionClient_Debug = QtGui.QAction(MainWindow)
        self.actionClient_Debug.setObjectName(_fromUtf8("actionClient_Debug"))
        self.actionMap_Debug = QtGui.QAction(MainWindow)
        self.actionMap_Debug.setObjectName(_fromUtf8("actionMap_Debug"))
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.actionOpen_2.setIcon(icon)
        self.actionOpen_2.setObjectName(_fromUtf8("actionOpen_2"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionStop_Script = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.actionStop_Script.setIcon(icon)
        self.actionStop_Script.setObjectName(_fromUtf8("actionStop_Script"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSelect_Client)
        self.menuTools.addAction(self.actionLoad_Script)
        self.menuTools.addAction(self.actionStart_Script)
        self.menuTools.addAction(self.actionStop_Script)
        self.menuView.addAction(self.actionClient_Debug)
        self.menuView.addAction(self.actionMap_Debug)
        self.menuFile_2.addAction(self.actionOpen_2)
        self.menuFile_2.addAction(self.actionSave)
        self.menuFile_2.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuView_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoad_Script)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart_Script)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStop_Script)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBot", None))
        self.menuFile.setTitle(_translate("MainWindow", "Select Client", None))
        self.menuTools.setTitle(_translate("MainWindow", "Run", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "Debug", None))
        self.menuFile_2.setTitle(_translate("MainWindow", "File", None))
        self.menuView_2.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "CrossHair", None))
        self.actionSelect_Client.setText(_translate("MainWindow", "Manual", None))
        self.actionStart_Script.setText(_translate("MainWindow", "Start Script", None))
        self.actionLoad_Script.setText(_translate("MainWindow", "Load Script", None))
        self.actionClient_Debug.setText(_translate("MainWindow", "Client Debug", None))
        self.actionMap_Debug.setText(_translate("MainWindow", "Map Debug", None))
        self.actionOpen_2.setText(_translate("MainWindow", "Edit...", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionStop_Script.setText(_translate("MainWindow", "Stop Script", None))